apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "zookeeper.pod-disruption-budget-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "zookeeper.labels" . | indent 4 | trim }}
spec:
  selector:
    matchLabels:
      {{ include "zookeeper.selector" . | indent 6  | trim }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
